sudo: required

services:
  - docker

before_install:
  - docker pull hello-world
  - docker run
        --detach --tty
        --name=test-machine
        --volume ${TRAVIS_BUILD_DIR}:/scratch/source/xacc
        --env TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
        --env CTEST_BUILD_NAME="$(curl -s https://raw.githubusercontent.com/ORNL-CEES/Cap/master/docker/get_build_info.sh | bash)"
        hello-world
  - docker ps -a
  - env

script:
  - echo "Hello World"
