sudo: required

services:
  - docker

before_install:
  - docker build -t xacc/xacc-fedora -f docker/fedora/devel/Dockerfile .
  - docker build -t xacc/xacc-ubuntu -f docker/ubuntu/devel/Dockerfile .
  - docker ps -a
  - env
  
script:
  - echo ""

