# Permalinks
#
permalink:           pretty

# Setup
title:               XACC
tagline:             'eXtreme-scale ACCelerator programming'
description:         'XACC is a programming framework and specification enabling quantum acceleration in existing classical computing in a manner that is language and hardware agnostic.'
url:                 https://ornl-qci.github.io/xacc
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Alex McCaskey
  url:               https://twitter.com/amccaskey2223
  email:             mccaskeyaj@ornl.gov

# Custom vars
version:             0.0.1
