# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: XACC - eXtreme-scale ACCelerator programming
email: mccaskeyaj@ornl.gov
description: "XACC is a programming framework and specification enabling quantum acceleration in existing classical computing in a manner that is language and hardware agnostic."
url: "https://ornl-qci.github.io"
baseurl: "/xacc"
twitter_username: amccaskey2223
github_username:  amccaskey

# Markdown support
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-redirect-from
 
# Sass support
sass:
    sass_dir: _sass
