# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: XACC
email: hemangsk@gmail.com
description: "A framework for programming extreme-scale accelerators for Post-Moore's Law heterogeneous computing."
url: "https://ORNL-QCI.github.io"
baseurl: "/xacc"
twitter_username: amccaskey2223
github_username:  amccaskey

# Build settings
markdown: kramdown

# Sass support
sass:
    sass_dir: _sass
